//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Avalonia;
using Avalonia.Styling;

namespace Enx.Atomic
{
    public partial class AtomicStyles : Styles
    {
        public AtomicStyles()
        {
            var style1 = new Style((Func<Selector, Selector>)((Selector selector) => //Selector
    Selectors.Class(
        Selectors.Is<Visual>(selector),
        "sm:max-lg:hidden")));
            style1.Setters.Add(new Setter(Visual.IsVisibleProperty, false));
            var container1 = new ContainerQuery((Func<StyleQuery, StyleQuery>)((StyleQuery query) => //StyleQuery
    StyleQueries.And(new StyleQuery[]{
        StyleQueries.Width(
            query,
            StyleQueryComparisonOperator.GreaterThanOrEquals,
            640),
        StyleQueries.Width(
            query,
            StyleQueryComparisonOperator.LessThan,
            1024)})), "top-level");
            container1.Add(style1);
            Add(container1);

            var style2 = new Style((Func<Selector, Selector>)((Selector selector) => //Selector
    Selectors.Class(
        Selectors.Is<Visual>(selector),
        "collapsed")));
            style2.Setters.Add(new Setter(Visual.OpacityProperty, 0));
            Add(style2);

        }
    }
}
