//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Avalonia;
using Avalonia.Styling;

namespace Enx.Atomic
{
    public partial class AtomicStyles : Styles
    {
        public AtomicStyles()
        {
            var style1 = new Style((Func<Selector, Selector>)((Selector selector) => //Selector
                Selectors.Class(
                    Selectors.Is<Visual>(selector),
                    "sm:max-lg:hidden")));
            style1.Setters.Add(new Setter(Visual.IsVisibleProperty,false));
            Add(style1);
            var style2 = new Style((Func<Selector, Selector>)((Selector selector) => //Selector
                Selectors.Class(
                    Selectors.Is<Visual>(selector),
                    "collapsed")));
            style2.Setters.Add(new Setter(Visual.OpacityProperty,0));
            Add(style2);
        }
    }
}