using System.Text;
using Enx.Atomic.Avalonia.CodeGen.Values;

namespace Enx.Atomic.Avalonia.CodeGen;

/// <summary>
/// Turns the <see cref="StyleValue.Resource"/>s a <see cref="AtomicGenerator{TTheme}"/> run encountered
/// (<see cref="AtomicGenerator{TTheme}.ResolvedResources"/>) into a static C# source file building an Avalonia
/// <c>ResourceDictionary</c> — the dictionary a generated <c>Styles</c> class's <c>DynamicResource</c> lookups
/// (emitted by <see cref="StyleEmitter"/>/<see cref="Values.DynamicResourceValueEmitter"/>) resolve against.
///
/// <para>
/// Each resource's <see cref="StyleValue.Resource.ThemeAccess"/> is compiled and invoked exactly once against
/// a real <typeparamref name="TTheme"/> instance to get its actual value — unlike <see cref="StyleEmitter"/>,
/// which works off the expression's <see cref="StyleValue.Resource.Key"/> alone as data, this step genuinely
/// needs the resolved value (to decide light/dark placement and to emit it via <see cref="ValueEmitterRegistry"/>),
/// so compiling and invoking is the right tool here — see <see cref="StyleValue.Resource"/>'s remarks.
/// </para>
///
/// <para>
/// A resolved value that isn't <see cref="IThemedValue.IsThemed"/> (including one that isn't
/// <see cref="IThemedValue"/> at all) becomes a single entry in the dictionary's own plain keys; an explicitly
/// themed one splits into <c>ResourceDictionary.ThemeDictionaries[ThemeVariant.Light]</c>/<c>[ThemeVariant.Dark]</c>.
/// </para>
/// </summary>
public static class ResourceDictionaryEmitter
{
    /// <param name="resources">The resources to emit, e.g. from <c>AtomicGenerator&lt;TTheme&gt;.ResolvedResources</c>.</param>
    /// <param name="theme">The real theme instance to resolve each resource's <see cref="StyleValue.Resource.ThemeAccess"/> against.</param>
    /// <param name="namespaceName">The namespace of the generated class.</param>
    /// <param name="className">The name of the generated class.</param>
    /// <param name="valueEmitters">Value emitters to use, in priority order. Defaults to <see cref="ValueEmitterRegistry.Default"/>.</param>
    public static string Emit<TTheme>(
        IReadOnlyDictionary<string, StyleValue.Resource> resources,
        TTheme theme,
        string namespaceName,
        string className,
        IEnumerable<IValueEmitter>? valueEmitters = null
    )
        where TTheme : class
    {
        var values = new ValueEmitterRegistry(valueEmitters);
        var namespaces = new HashSet<string> { "Avalonia.Controls", "Avalonia.Styling" };
        var global = new StringBuilder();
        var light = new StringBuilder();
        var dark = new StringBuilder();
        var hasThemed = false;

        foreach (var (key, resource) in resources.OrderBy(kv => kv.Key, StringComparer.Ordinal))
        {
            var resolved = resource.ThemeAccess.Compile().DynamicInvoke(theme);
            var keyText = CSharpLiteral.String(key);

            if (resolved is IThemedValue { IsThemed: true } themed)
            {
                hasThemed = true;
                light.AppendLine($"        light[{keyText}] = {values.Emit(themed.LightValue, namespaces)};");
                dark.AppendLine($"        dark[{keyText}] = {values.Emit(themed.DarkValue, namespaces)};");
            }
            else
            {
                var value = resolved is IThemedValue notThemed ? notThemed.LightValue : resolved;
                global.AppendLine($"        resources[{keyText}] = {values.Emit(value, namespaces)};");
            }
        }

        var file = new StringBuilder();
        file.AppendLine("//------------------------------------------------------------------------------");
        file.AppendLine("// <auto-generated>");
        file.AppendLine("//     This code was generated by Enx.Atomic.Avalonia.CodeGen.");
        file.AppendLine("//     Changes to this file may cause incorrect behavior and will be lost if the");
        file.AppendLine("//     code is regenerated.");
        file.AppendLine("// </auto-generated>");
        file.AppendLine("//------------------------------------------------------------------------------");
        file.AppendLine("#nullable enable");
        foreach (var ns in namespaces.Where(ns => ns != namespaceName).OrderBy(ns => ns, StringComparer.Ordinal))
            file.AppendLine($"using {ns};");
        file.AppendLine();
        file.AppendLine($"namespace {namespaceName};");
        file.AppendLine();
        file.AppendLine($"public static class {className}");
        file.AppendLine("{");
        file.AppendLine("    public static ResourceDictionary Build()");
        file.AppendLine("    {");
        file.AppendLine("        var resources = new ResourceDictionary();");
        file.Append(global);
        if (hasThemed)
        {
            file.AppendLine("        var light = new ResourceDictionary();");
            file.Append(light);
            file.AppendLine("        var dark = new ResourceDictionary();");
            file.Append(dark);
            file.AppendLine("        resources.ThemeDictionaries[ThemeVariant.Light] = light;");
            file.AppendLine("        resources.ThemeDictionaries[ThemeVariant.Dark] = dark;");
        }
        file.AppendLine("        return resources;");
        file.AppendLine("    }");
        file.AppendLine("}");

        return file.ToString();
    }
}
