using System.Text;
using Enx.Atomic.Avalonia.CodeGen.Values;

namespace Enx.Atomic.Avalonia.CodeGen;

/// <summary>
/// Turns a set of resolved <see cref="StringifiedUtil"/>s into a static C# source file — a <c>Styles</c>
/// subclass building each one directly, no runtime token resolution involved. Works entirely off data
/// (<see cref="StringifiedUtil.SelectorData"/>/<c>ContainerQueryData</c>, <see cref="Setter"/> values), never
/// compiling an <see cref="System.Linq.Expressions.Expression"/> and decompiling the result — see the "Build-time
/// C# code generation" and "History" sections of <c>ARCHITECTURE.md</c> for why that distinction matters.
/// </summary>
public static class StyleEmitter
{
    /// <param name="utils">The resolved styles to emit, e.g. from <c>AtomicGenerator&lt;TTheme&gt;.Generate(...)</c>.</param>
    /// <param name="namespaceName">The namespace of the generated class.</param>
    /// <param name="className">The name of the generated <c>Styles</c> subclass.</param>
    /// <param name="containerName">The container name used for every container-query-scoped style — matches <c>AtomicConfiguration.ContainerName</c>.</param>
    /// <param name="valueEmitters">Value emitters to use, in priority order. Defaults to <see cref="ValueEmitterRegistry.Default"/>.</param>
    public static string Emit(
        IReadOnlyList<StringifiedUtil> utils,
        string namespaceName,
        string className,
        string containerName = "top-level",
        IEnumerable<IValueEmitter>? valueEmitters = null
    )
    {
        var values = new ValueEmitterRegistry(valueEmitters);
        var namespaces = new HashSet<string> { "Avalonia.Styling" };
        var embeddedTypes = new Dictionary<string, string>();
        var body = new StringBuilder();

        for (var i = 0; i < utils.Count; i++)
        {
            var util = utils[i];
            var styleVar = $"style{i + 1}";

            var selectorText = SelectorEmitter.Emit(util.SelectorData, namespaces, values);
            body.AppendLine($"        var {styleVar} = new Style(selector => {selectorText});");

            foreach (var setter in util.Body)
            {
                if (setter.Property is null)
                    continue;

                var declaringType = setter.Property.OwnerType;
                var embeddableSource = EmittableGhostPropertyEmitter.TryGetEmbeddableSource(declaringType);

                string propertyText;
                if (embeddableSource is not null)
                {
                    // The declaring type's own assembly may not be a dependency of the project this file
                    // compiles into (see EmittableGhostPropertyHostAttribute) — embed a self-contained copy
                    // once instead of referencing the original.
                    embeddedTypes[declaringType.Name] = embeddableSource;
                    propertyText =
                        $"{declaringType.Name}.{AvaloniaPropertyNaming.GetFieldName(setter.Property, declaringType)}";
                }
                else
                {
                    foreach (var ns in CSharpTypeNaming.GetNamespaces(declaringType))
                        namespaces.Add(ns);
                    propertyText = AvaloniaPropertyNaming.GetExpression(setter.Property);
                }

                var valueText = values.Emit(setter.Value, namespaces);
                body.AppendLine($"        {styleVar}.Setters.Add(new Setter({propertyText}, {valueText}));");
            }

            if (util.ContainerQueryData is null)
            {
                body.AppendLine($"        Add({styleVar});");
            }
            else
            {
                var queryVar = $"{styleVar}Query";
                var queryText = StyleQueryEmitter.Emit(util.ContainerQueryData, namespaces);
                body.AppendLine(
                    $"        var {queryVar} = new ContainerQuery(query => {queryText}, {CSharpLiteral.String(containerName)});"
                );
                body.AppendLine($"        {queryVar}.Add({styleVar});");
                body.AppendLine($"        Add({queryVar});");
            }
        }

        var file = new StringBuilder();
        file.AppendLine("//------------------------------------------------------------------------------");
        file.AppendLine("// <auto-generated>");
        file.AppendLine("//     This code was generated by Enx.Atomic.Avalonia.CodeGen.");
        file.AppendLine("//     Changes to this file may cause incorrect behavior and will be lost if the");
        file.AppendLine("//     code is regenerated.");
        file.AppendLine("// </auto-generated>");
        file.AppendLine("//------------------------------------------------------------------------------");
        // Files matching the "generated code" convention (this one does, both by name and by the header
        // above) default to a nullable-oblivious context regardless of the project's own <Nullable> setting,
        // unless the file states its own context explicitly — needed for the nullable annotations an embedded
        // EmittableGhostPropertyHostAttribute type's source can use (e.g. GridDefinitions' ColumnDefinitions?).
        file.AppendLine("#nullable enable");
        foreach (var ns in namespaces.Where(ns => ns != namespaceName).OrderBy(ns => ns, StringComparer.Ordinal))
            file.AppendLine($"using {ns};");
        file.AppendLine();
        file.AppendLine($"namespace {namespaceName};");
        file.AppendLine();
        file.AppendLine($"public partial class {className} : Styles");
        file.AppendLine("{");
        file.AppendLine($"    public {className}()");
        file.AppendLine("    {");
        file.Append(body);
        file.AppendLine("    }");
        file.AppendLine("}");

        foreach (var source in embeddedTypes.OrderBy(kv => kv.Key, StringComparer.Ordinal).Select(kv => kv.Value))
        {
            file.AppendLine();
            file.Append(source);
        }

        return file.ToString();
    }
}
